spring:
  datasource:
    username: root
    password: 123456
    # 加入时区报错了，就增加一个时区的配置就OK了serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/city?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
